### PR TITLE
Search and Post's subreddit function.

### PR DESCRIPTION
**Pull request by Stepepper**
Added a Function for Post where it gets the post's subreddit,
and a function for searching.

I added two enums, one that is called Sorting and the other is called TimeSorting. 

```C#
public enum Sorting
    {
        Relevance,
        New,
        Top,
        Comments
    }

    public enum TimeSorting
    {
        All,
        Hour,
        Day,
        Week,
        Month,
        Year
    }
```

The search function still works if you update it, since it has it's default value on what it used to be, but you can use the function now like so:
```C#
var posts = redditbot.Search<Post>(searchQuery, Sorting.Top, TimeSorting.Month).Take<Post>(25);
```

The GetSubreddit simply returns a string, which you can use like this:
```C#
foreach(var post in allPosts)
            {
                if (SubredditsToIgnore.Any(s=>post.GetSubreddit().StartsWith(s)))
                {
                    Log.Add("Ignored post because it had an ignored subreddit: " + Environment.NewLine + "\t" + post.Title);
                    continue;
                };
            }
```

Simply ```post.GetSubreddit()```.
It uses Regex, acquiring the Subreddit string from the Permalink.

### CODE REVIEW

**Comment by SirCmpwn** [comment]
Search changes look good. However, `GetSubreddit()` I don't like. There's a subreddit_id field that comes from the JSON, how about we map it and have a property that gets the relevant subreddit properly.

**Comment by Stepepper** [comment]
Oh, I searched for it but I couldn't find it. 
I'll look into it.

**Comment by Stepepper** [comment]
However I have no idea how this exactly works. There's a JSON property simply called subreddit it seems, inside of `/comments/{0}.json`.

But this does not work:
```C#
[JsonProperty("subreddit")]
public string Subreddit { get; }
```

What is a quick and easy way of fetching that?

**Comment by SirCmpwn** [comment]
Look at how this works:

https://github.com/SirCmpwn/RedditSharp/blob/master/RedditSharp/Things/Post.cs#L53-L63

What you want to do is something like this:

[JsonProperty("subreddit_id")]
public string SubredditId { get; }

And then a property that exposes a getter which fetches the full Subreddit object from the API.

**Comment by Stepepper** [comment]
Oh, no need! I got it fixed by adding a `set;` after it.
I'll push this one.

**Comment by SirCmpwn** [comment]
That does not fix it...

**Comment by Stepepper** [comment]
```C#
if (SubredditsToIgnore.Any(s=>post.Subreddit.StartsWith(s)))
                {
                    Log.Add("Ignored post because it had an ignored subreddit: " + Environment.NewLine + "\t" + post.Title);
                    continue;
                }
```

```
Ignored post because it had an ignored subreddit: 
	Match Thread: Spain vs The Netherlands - World Cup Group B
Ignored post because it had an ignored subreddit: 
	Match Thread: Netherlands vs Mexico - Round of 16
Ignored post because it had an ignored subreddit: 
	Match Thread: Australia vs The Netherlands - Group B
Ignored post because it had an ignored subreddit: 
	Post Match Thread: Netherlands 3 - 4 United States
Ignored post because it had an ignored subreddit: 
	Match Thread: Netherlands vs Argentina
Ignored post because it had an ignored subreddit: 
	Match Thread: Brazil v Netherlands
```

But it works right now, while without Set; it didn't work. The ignored subreddits are leagueoflegends and soccer. All these threads are from /r/soccer.

**Comment by SirCmpwn** [comment]
If you're going to use the property name "Subreddit", it has to return an actual `Subreddit`. I suggest you call it "SubredditName" and if you don't feel like implementing the rest, then don't.

**Comment by Stepepper** [comment]
Edited according to your will. 
Is it better now?

**Comment by SirCmpwn** [comment]
Don't call it `GetSubreddit`. Just call it `Subreddit`. It's a property that returns a subreddit, it doesn't (from an external standpoint) behave like a method.

**Comment by Stepepper** [comment]
I have no idea what to do now, with this pull request. Do I close it?

**Comment by SirCmpwn** [comment]
It looks good now. I don't get notified when you push new commits, only when you leave comments.

**Comment by Stepepper** [comment]
Oh I see, thanks.

**Pull request merged**
