### PR TITLE
List of Subreddits related to param.

### PR DESCRIPTION
**Pull request by tomnolan95**
Just added a new link to Reddit class and method to allow someone to get a list of subreddits related to a search query. I want it in order to get a list of recommended subreddits related to frequently commented subreddits of a user.

### CODE REVIEW

**Comment by tomnolan95** [comment]
Ignore the first commit, VS didn't pick up the changes to the Reddit class for some reason, so had to re-commit.

**Comment by SirCmpwn** [comment]
You need to fix your editor fucking with the line endings. I can't read the diff and I can't review this pull request.

**Comment by tomnolan95** [comment]
Cool, not sure why it did that, I'll fix it when I get back into the house.

**Comment by tomnolan95** [comment]
Hey man, so I've had a look in Visual Studio and I can't see what it's done at all. I literally forked the project, pulled it, added a variable and a method and changed nothing else. I don't know what it would have done to the line endings, I suppose you wouldn't have any ideas on how to fix it? (Sorry by the way, pretty new to Git so not entirely sure what to do, sorry again for the inconvenience).

**Comment by SirTony** [comment]
It's probably your git configuration that's messed up.

Check your EOL settings with `git config --global core.autocrlf`

If `core.autocrlf` is `false` set it to true with `git config --global core.autocrlf true`.

**Comment by tomnolan95** [comment]
According to Git Bash core.autocrlf is set to true, so not entirely sure what's going on at all.

**Pull request closed without merging**
