### PR TITLE
Implement compatibility for WebProxies

### PR DESCRIPTION
**Pull request by SmithsonianDSP**
Adds an implementation that allows users to configure a `WebProxy` that will be used for all requests. Addresses issue #51. 

To use, call this method at start:
```cs
RedditSharp.HttpWebReqProxy.SetupWebRequestProxy("http://proxyaddress", "domain\\username", "password");
```

Can also disable the proxy configuration settings later by calling `RedditSharp.HttpWebReqProxy.DisableWebRequestProxy();`

I *think* I hit all of the places where `System.Net.HttpWebRequest` are created and used (if I missed any, I haven't caught it in my initial testing).

&nbsp;

---

(Note: C# isn't my primary language of experience, so I apologize if there are any *faux pas* that I've made. Let me know if there's anything I should change or fix.)

### CODE REVIEW

**Comment by SirCmpwn** [comment]
Thank you, but the same thing can be (and should be) accomplished by providing an alternate implementation of IWebAgent that sets up the proxy for each request, rather than by extending RedditSharp to fulfill every niche situation itself.

**Comment by SmithsonianDSP** [comment]
>but the same thing can be (and should be) accomplished by providing an alternate implementation of IWebAgent that sets up the proxy for each request

If that is the case, then `RedditSharp.WebAgent` should be inheritable and `CreateRequest` (and other methods and functions) should be Overridable so this would be a much simpler thing to do, instead of having to completely rewrite the entire implementation of WebAgent (which is the opposite of [D.R.Y.](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself))

**Comment by SirCmpwn** [comment]
That's fair, you should take that strategy in a seperate PR.

**Comment by CrustyJew** [comment]
I second both of these motions. I re-implemented WebAgent for my own purposes and it was annoying not being able to inherit from it. But I believe I did update in a previous pull request all the locations I knew of so that you could pass in a custom IWebAgent and not conflict with the packaged WebAgent implementation.

**Pull request closed without merging**
