### PR TITLE
Unit tests on Authentication.

### PR DESCRIPTION
**Pull request by IAmAnubhavSaini**
Works as expected.

### CODE REVIEW

**Comment by SirCmpwn** [comment]
Visual Studio's testing tools are:

1. Closed source
2. Not available on systems other than Windows

**Comment by IAmAnubhavSaini** [comment]
Is NUnit fine?

**Comment by SirCmpwn** [comment]
Yes, but there's a larger problem with unit testing for this project. I don't want us hitting reddit.com whenever we run our test suite. You may want to read the previous attempts:

https://github.com/SirCmpwn/RedditSharp/pull/138

https://github.com/SirCmpwn/RedditSharp/pull/118

**Comment by IAmAnubhavSaini** [comment]
Hitting public API every time tests run didn't cross my mind.

Well you can get a blog post out of it - "Everybody is a tester"  :smile: 

But I anyway will refactor code on my fork.

**Pull request closed without merging**
