### PR TITLE
Added Contest Mode Toggle Ability

### PR DESCRIPTION
**Pull request by BrianJWhite**
Added the ability to change a post to and from Contest Mode.

### CODE REVIEW

**Comment by SirCmpwn** [comment]
I can't evaluate this pull request because you changed the line endings. Look at the files changed tab to see the effect of this.

**Comment by BrianJWhite** [comment]
Oh sorry.  I will redo it.  Never submitted anything before :)

**Comment by SirCmpwn** [comment]
It's alright, just a simple mistake. You shouldn't have to resubmit - just push additional commits to your master branch and they'll be added to the pull request.

**Comment by BrianJWhite** [comment]
Ok I think I got it.  If you want to take another look.

**Comment by SirCmpwn** [comment]
Yes, you've got it, but there's one more thing to deal with. Now you have 11 commits to make one minor change - use `git rebase -i HEAD~10` to "squash" them all into a single commit, then `git push --force`.

**Comment by BrianJWhite** [comment]
Ok, I think that may be good now...It's been a long time since I've used git.

**Comment by SirCmpwn** [comment]
Great, thanks!

**Pull request merged**
