### PR TITLE
Addition to search: cloud search

### PR DESCRIPTION
**Pull request by emilm**
Hi, I added some basic support for cloud search. And I made class that makes it easy to build such a query, instead of messing with string.format. :)

Still unsure about my enum -> string. I know newtonsoft does this, but you have to go through a lot of hoops, to get the actual string.

### CODE REVIEW

**Comment by SirCmpwn** [comment]
This looks good to me from a cursory glance, but I'll have to test it out. Would also like some feedback from other people involved in RedditSharp.

**Comment by epvanhouten** [comment]
There are some strange smells around Ranges. It seems to be like they
should be their own StringCloudSearchQueryBuilderItem and solve their
special ToString problems themselves. That would then simply the BuildQuery
operation enough that it could use a foreach/linq implementation more
cleanly.

Erick

**Comment by emilm** [comment]
Yeah you could have one for range, and remove Value from the base class, and make them utilize their own private value properties.

**Comment by SirTony** [comment]
> Still unsure about my enum -> string

You don't need a custom attribute to get the name of an enum field as a string, simply calling `ToString` does that. You can then just use `ToLowerInvariant` to get the reddit-friendly name. You can see I did that with spam filter settings [here](https://github.com/SirCmpwn/RedditSharp/blob/e200c7aec12702bf6ed8004789f8f25a598cea85/RedditSharp/SubredditSettings.cs#L194-L196).

``` csharp
enum ShortType
{
    Relevance,
    ...
}

var name = ShortType.Relevance.ToString().ToLowerInvariant(); // relevance
```

**Comment by emilm** [comment]
Yes, I know this. But I did it in case the enum name would differ from the string. It matches in this case, but suddenly you run into a weird string that doesn't make sense in an enum name

**Comment by SirCmpwn** [comment]
Bump.

**Comment by SirCmpwn** [comment]
Closing due to inactivity.

**Pull request closed without merging**
