### PR TITLE
List of Subreddits related to param.

### PR DESCRIPTION
**Pull request by tomnolan95**
I'm hoping this time that the line endings are okay, it was * text =  auto in .gitattributes that was messing with them. Sorry again if this isn't okay.

### CODE REVIEW

**Comment by SirCmpwn** [comment]
How about "SearchSubreddits"?

**Comment by tomnolan95** [comment]
As in change the name of the function? I'm not if it's alright that I edited the .gitattributes but if it's left the way it is at the moment Visual Studio will auto-correct the line-endings which was the problem with my other pull request.

**Comment by SirCmpwn** [comment]
The line endings are fine, and yes, I was suggesting a new name for the function.

**Comment by tomnolan95** [comment]
Yeah 'SearchSubreddits' is fine by me, I'll change it and re-push then? Sorry if I'm a pain in the ass, haven't been using Git very long.

**Comment by SirCmpwn** [comment]
It's fine. Make the change, then do another commit and push it to master. It'll show up in this pull request automatically.

**Comment by tomnolan95** [comment]
Done, thanks for help.

**Comment by SirCmpwn** [comment]
Thanks!

**Pull request merged**
