### PR TITLE
added mod actions: ability to send PM via subreddit & ability to sticky a post 

### PR DESCRIPTION
**Pull request by artofdarkness123**
added ability to send PM via subreddit (mod action)
added ability to sticky a post (mod action)

### CODE REVIEW

**Comment by CrustyJew** [comment]
The line endings appear to be messed up for this pull request. Can you fix that please?

**Comment by CrustyJew** [comment]
Looks like the line endings are still wrong. Look at the diff and it's
saying all lines are different

**Comment by artofdarkness123** [comment]
@CrustyJew   I've never contributed to another GitHub project before. What do you mean the line endings are wrong? I fixed all the conflicts caused by merging. I'm using a Windows machine and VS2015. Does that affect line endings somehow?

**Comment by artofdarkness123** [comment]
How do you know the line endings are *wrong*. If you're not a computer? Does it really mater since this is a C# project. Who isn't using Windows for this project?

**Comment by CrustyJew** [comment]
Just looking at the diff online you can tell because it's saying everything
changed when it really didn't.

The line endings are linux vs windows and it does matter so it makes diffs
readable and does mix endings which can cause problems with compilers

**Comment by artofdarkness123** [comment]
ok i converted all the line endings in notepad++ and the file diff looks better.

**Comment by CrustyJew** [comment]
Ok, sorry to make this difficult, but can you merge in the changes again and update your branch. I think I fixed the line ending issues once and for all now.

**Comment by artofdarkness123** [comment]
@CrustyJew done. hope everything works this time

**Comment by CrustyJew** [comment]
Thanks!

**Pull request merged**
