### PR TITLE
Add automated tests.

### PR DESCRIPTION
**Pull request by thehereward**
Adding tests but not using NCrunch this time.

### CODE REVIEW

**Comment by SirCmpwn** [comment]
Bump.

**Comment by thehereward** [comment]
Sorry, I've been ill recently. I'll try to have a look once I've recovered.

**Comment by SirCmpwn** [comment]
No hurry, just making sure it wasn't forgotten. Get well soon.

**Comment by thehereward** [comment]
Okay, sorry for the delay; it's taken me awhile to get back on my feet.

The 'project type' not supported by Xamarin is 'MSTest', removing the guid: `{3AC096D0-A1C2-E12C-1390-A8335801FDAB}` from the .csproj file solved this. I have pushed this change to this branch.

Unfortunately this does not solve everything and I am not familiar enough with mono to know what to do. I cannot get the tests to run with the project as is; I can by adding an NUnit Library Project (like here  http://blog.falafel.com/hold-right-learning-xamarin-unit-tests/) but the all error when trying to load Newtonsoft.JSON.

I will try to have another look in the not too distant future; I hope I am just missing something rather obvious. I would, however, appreciate any constructive suggestions!

**Comment by SirCmpwn** [comment]
Closing this for now, send another PR if you ever get around to it.

**Pull request closed without merging**
